Updated Release Notes With Kodular Eagle Version 1.4D.0 & Fixed a Wrong Picture URL
Kodular/Documentation pull request #70
Opened 2020-08-31 07:44 UTC by hrichiksite

Updated Release Notes With Kodular Eagle Version 1.4D.0 & Fixed a Wrong Picture URL

![image](https://user-images.githubusercontent.com/57860916/91695205-6b377700-eb8b-11ea-821b-46e2599f55ba.png)

2020-08-31 08:33 UTC, Vishwas-Adiga approved these changes

2020-08-31 18:26 UTC, barreeeiroo requested changes
Hi @hrichiksite!
Thanks for your contribution. Actually, I had already made the changes to the docs yesterday, but I forgot to commit them. 😓
But the change to fix the Image URL is totally fine, so do you removing everything else, to merge your changes?

2020-09-01 03:41 UTC, hrichiksite commented
I have updated the eagle.md to match your changes 😄 
Now, it will no more conflict with `Kodular:master` so you can merge easily.

2020-09-03 07:55 UTC, barreeeiroo approved these changes

2020-09-03 07:56 UTC, merged